baseURL = "https://anandhs.github.io/what-why-how/"
languageCode = "en-us"
title = "what why and how"
theme = "cleanlite"
[pagination]
  pagerSize = 10


enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "A clean markdown blog with tags, categories, and series."
